# Generated by Django 5.1.15 on 2026-08-10 13:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qa', '0004_qamodel_codigo_error_alter_qamodel_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorGroupModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('exception_type', models.CharField(max_length=255)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('nivel', models.CharField(choices=[('warning', 'WARNING'), ('error', 'ERROR'), ('critical', 'CRITICAL')], default='error', max_length=10)),
                ('estado', models.CharField(choices=[('nuevo', 'NUEVO'), ('en_progreso', 'EN_PROGRESO'), ('resuelto', 'RESUELTO'), ('ignorado', 'IGNORADO')], default='nuevo', max_length=15)),
                ('ambiente', models.CharField(choices=[('Development', 'Development'), ('Staging', 'Staging'), ('Production', 'Production')], default='Development', max_length=20)),
                ('http_method', models.CharField(blank=True, default='', max_length=10)),
                ('path', models.CharField(blank=True, default='', max_length=500)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('stack_frames', models.JSONField(blank=True, default=list)),
                ('stack_trace_text', models.TextField(blank=True, default='')),
                ('count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField()),
                ('resolucion_nota', models.TextField(blank=True, default='')),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qa_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errores_vinculados', to='qa.qamodel')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errores_resueltos', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errores_reportados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'errores_grupos',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['-last_seen'], name='errores_last_seen_idx'), models.Index(fields=['estado', 'ambiente'], name='errores_estado_amb_idx'), models.Index(fields=['nivel'], name='errores_nivel_idx')],
            },
        ),
    ]
