# Generated by Django 5.1.15 on 2026-08-10 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errores', '0001_initial'),
        ('qa', '0004_qamodel_codigo_error_alter_qamodel_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='errorgroupmodel',
            name='errores_estado_amb_idx',
        ),
        migrations.RemoveField(
            model_name='errorgroupmodel',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='errorgroupmodel',
            name='resolucion_nota',
        ),
        migrations.RemoveField(
            model_name='errorgroupmodel',
            name='resuelto_en',
        ),
        migrations.RemoveField(
            model_name='errorgroupmodel',
            name='resuelto_por',
        ),
        migrations.AddIndex(
            model_name='errorgroupmodel',
            index=models.Index(fields=['ambiente'], name='errores_ambiente_idx'),
        ),
    ]
