# Generated by Django 5.1.15 on 2026-08-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errores', '0002_remove_errorgroupmodel_errores_estado_amb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorgroupmodel',
            name='ocurrencias_recientes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
