# Generated by Django 5.1.15 on 2026-08-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errores', '0003_errorgroupmodel_ocurrencias_recientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorgroupmodel',
            name='ai_diagnostico',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errorgroupmodel',
            name='ai_diagnostico_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
