# Generated by Django 5.1.15 on 2026-08-06 14:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QaModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                ("sistema", models.CharField(max_length=100)),
                ("modulo", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=50)),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("alta", "ALTA"),
                            ("media", "MEDIA"),
                            ("baja", "BAJA"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("nueva", "NUEVA"),
                            ("en_proceso", "EN_PROCESO"),
                            ("pendiente_validacion", "PENDIENTE_VALIDACION"),
                            ("aprobada", "APROBADA"),
                            ("rechazada", "RECHAZADA"),
                            ("correccion", "CORRECCION"),
                            ("validacion_final", "VALIDACION_FINAL"),
                            ("cerrada", "CERRADA"),
                        ],
                        default="nueva",
                        max_length=25,
                    ),
                ),
                ("fecha", models.DateField()),
                ("ambiente", models.CharField(max_length=100)),
                ("resultado_esperado", models.TextField()),
                ("resultado_obtenido", models.TextField(blank=True, default="")),
                ("observaciones", models.TextField(blank=True, default="")),
                ("tiempo_invertido_minutos", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "qa_pruebas",
                "ordering": ["-created_at"],
            },
        ),
    ]
