# Generated by Django 5.1.15 on 2026-08-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qamodel",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="qamodel",
            name="fecha",
        ),
        migrations.RemoveField(
            model_name="qamodel",
            name="observaciones",
        ),
        migrations.RemoveField(
            model_name="qamodel",
            name="sistema",
        ),
        migrations.RemoveField(
            model_name="qamodel",
            name="tiempo_invertido_minutos",
        ),
        migrations.RemoveField(
            model_name="qamodel",
            name="version",
        ),
        migrations.AddField(
            model_name="qamodel",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("ui_design", "Diseño / UI"),
                    ("ux_flow", "Comportamiento / UX"),
                    ("qa_test", "Prueba Manual QA"),
                ],
                default="qa_test",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="qamodel",
            name="device_or_browser",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="qamodel",
            name="figma_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="qamodel",
            name="imagen_antes",
            field=models.ImageField(blank=True, null=True, upload_to="qa/antes/%Y/%m/"),
        ),
        migrations.AddField(
            model_name="qamodel",
            name="imagen_despues",
            field=models.ImageField(
                blank=True, null=True, upload_to="qa/despues/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="qamodel",
            name="pasos_reproduccion",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="qamodel",
            name="ambiente",
            field=models.CharField(
                choices=[
                    ("Development", "Development"),
                    ("Staging", "Staging"),
                    ("Production", "Production"),
                ],
                default="Staging",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="qamodel",
            name="prioridad",
            field=models.CharField(
                choices=[("alta", "ALTA"), ("media", "MEDIA"), ("baja", "BAJA")],
                default="media",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="qamodel",
            name="resultado_esperado",
            field=models.TextField(blank=True, default=""),
        ),
    ]
