# Generated by Django 5.1.15 on 2026-08-07 00:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TareaModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, default="")),
                (
                    "rama_github",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("pr_url", models.URLField(blank=True, default="")),
                ("fecha_limite", models.DateField(blank=True, null=True)),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("alta", "ALTA"),
                            ("media", "MEDIA"),
                            ("baja", "BAJA"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("hacer", "HACER"),
                            ("en_curso", "EN_CURSO"),
                            ("en_proceso", "EN_PROCESO"),
                            ("terminado", "TERMINADO"),
                            ("cerrado", "CERRADO"),
                        ],
                        default="hacer",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tareas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tareas",
                "ordering": ["-created_at"],
            },
        ),
    ]
