import type { ExecutionRecord } from "@/modules/qa/types/qa.types";

export const QA_HISTORIAL_MOCK_DATA: ExecutionRecord[] = [
  {
    id: "EXEC-9042",
    suiteName: "Regresión Completa - Módulo de Pagos",
    environment: "Staging",
    triggerType: "auto",
    triggeredBy: "GitHub Actions (CI/CD)",
    duration: "2m 14s",
    passedCount: 42,
    failedCount: 0,
    totalCount: 42,
    status: "passed",
    timestamp: "Hoy, 09:15 AM",
  },
  {
    id: "EXEC-9041",
    suiteName: "Pruebas E2E - Flujo de Autenticación",
    environment: "Production",
    triggerType: "manual",
    triggeredBy: "Ana Martínez",
    duration: "45s",
    passedCount: 12,
    failedCount: 2,
    totalCount: 14,
    status: "failed",
    timestamp: "Hoy, 08:30 AM",
  },
  {
    id: "EXEC-9040",
    suiteName: "Smoke Test - Notificaciones Push",
    environment: "Development",
    triggerType: "manual",
    triggeredBy: "Carlos Ruiz",
    duration: "1m 02s",
    passedCount: 8,
    failedCount: 0,
    totalCount: 8,
    status: "passed",
    timestamp: "Ayer, 05:40 PM",
  },
  {
    id: "EXEC-9039",
    suiteName: "Prueba de Carga - Endpoints de Facturación",
    environment: "Staging",
    triggerType: "auto",
    triggeredBy: "Cron Scheduler",
    duration: "5m 20s",
    passedCount: 18,
    failedCount: 1,
    totalCount: 19,
    status: "failed",
    timestamp: "12 Ago, 2026 - 11:00 PM",
  },
  {
    id: "EXEC-9038",
    suiteName: "Validación de Roles y Permisos",
    environment: "Staging",
    triggerType: "manual",
    triggeredBy: "David M.",
    duration: "12s",
    passedCount: 0,
    failedCount: 0,
    totalCount: 15,
    status: "aborted",
    timestamp: "11 Ago, 2026 - 03:20 PM",
  },
];
